"""empty message

Revision ID: c96bcb23a39a
Revises: 1a761e2677d9
Create Date: 2023-07-13 12:53:40.897581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96bcb23a39a'
down_revision = '1a761e2677d9'
branch_labels = None
depends_on = None

import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.create_unique_constraint('unique_board_name_in_project', ['project_id', 'name'])

    with op.batch_alter_table('tasks', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')

    with op.batch_alter_table('boards', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.drop_constraint('unique_board_name_in_project', type_='unique')

    # ### end Alembic commands ###