"""empty message

Revision ID: 715de1e18ec9
Revises: 64259b6f9fe9
Create Date: 2023-06-16 00:40:34.268324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "715de1e18ec9"
down_revision = "64259b6f9fe9"
branch_labels = None
depends_on = None

import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=25), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["boards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    if environment == "production":
        op.execute(f"ALTER TABLE cards SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cards")
    # ### end Alembic commands ###
