"""empty message

Revision ID: 28add6197b5f
Revises: 13ca6b9311d0
Create Date: 2023-07-24 18:07:59.928748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28add6197b5f'
down_revision = '13ca6b9311d0'
branch_labels = None
depends_on = None

import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###