"""empty message

Revision ID: 5d7f4b08c415
Revises: 1a761e2677d9
Create Date: 2023-06-22 14:30:44.991178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7f4b08c415'
down_revision = '1a761e2677d9'
branch_labels = None
depends_on = None

import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.create_unique_constraint('unique_board_name_in_project', ['project_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.drop_constraint('unique_board_name_in_project', type_='unique')

    # ### end Alembic commands ###