"""empty message

Revision ID: 7c808829ba70
Revises: 28add6197b5f
Create Date: 2023-09-25 11:07:25.481009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c808829ba70'
down_revision = '28add6197b5f'
branch_labels = None
depends_on = None

import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.drop_column('imageUrl')

    with op.batch_alter_table('projects', schema=SCHEMA if environment == "production" else None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###